<form style="max-width:80%;" id="event_form" method="post" action="/edit_room_post?room_id=<?= $this->room_id ?>" class="light">
    <h2>Промяна на настройки за зала</h2>
    <p>
        <label for="name" class="required">Наименование на залата:</label>
        <input class="form-control" type="text" name="name" value="<?= $this->room['title'] ?>" required />
    </p>
    <p>
        <label for="img_url">URL на картинката:</label>
        <input class="form-control" type="text" name="img_url" value="<?= $this->room['img_url'] ?>" />
    </p>
    <p>
        <label for="color">Цвят:</label>
        <input class="form-control" type="color" name="color" value="<?= $this->room['color'] ?>" />
    </p>

    <p class="mb-0 text-right">
        <input type="submit" class="btn btn-primary" value="Приложи" />
    </p>
</form>
