<form method="get">
    <label for="search">Търсене на събития</label>
    <input type="text" name="search" size="40" />
    <input type="submit" value="търси" />
    <?php if ($this->search) {?>
        <input type="button" value="покажи всички" onclick="location.replace('/rooms/<?= $this->room_id ?>/events');" />
    <?php } ?>
</form>

<form method="post" action="/delete_events" id="events_form">
    <table>
        <tr>
            <th>
                <!-- selector -->
            </th>
            <th>
                <a href="<?= get_sort_link('id') ?>">Номер</a>
            </th>
            <th>
                <a href="<?= get_sort_link('created') ?>">Клеймо</a>
            </th>
            <th>
                <a href="<?= get_sort_link('date') ?>">Дата</a>
            </th>
            <th>
                <a href="<?= get_sort_link('start_time') ?>">Начален час</a>
            </th>
            <th>
                <a href="<?= get_sort_link('end_time') ?>">Краен час</a>
            </th>
            <th>
                <a href="<?= get_sort_link('ogranizer') ?>">Организатор</a>
            </th>
            <th>
                <a href="<?= get_sort_link('name') ?>">Наименование</a>
            </th>
            <th>
                <a href="<?= get_sort_link('user') ?>">Лице за контакт</a>
            </th>
            <th>
                <a href="<?= get_sort_link('phone') ?>">Телефон</a>
            </th>
            <th>
                <a href="<?= get_sort_link('email') ?>">Имейл</a>
            </th>
            <th>
                <a href="<?= get_sort_link('other') ?>">Допълнителна информация</a>
            </th>
            <th>
                Повтаряемост
            </th>
            <th>
                Действия
            </th>
        </tr>
        <?php foreach ($this->events as $e) { ?>
            <tr>
                <td>
                    <input type="checkbox" name="event[]" value="<?= $e['real_id'] ?>" onchange="select_event(this)"></checkbox>
                </td>
                <td>
                    <?= $e['real_id'] ?>
                </td>
                <td>
                    <?= $e['creation_time']?>
                </td>
                <td>
                    <?= $e['start']->format("d/m/Y") ?>
                </td>
                <td>
                    <?= $e['start']->format("H:s") ?>
                </td>
                <td>
                    <?= $e['end']->format("H:s") ?>
                </td>
                <td>
                    <?= $e['organizer'] ?>
                </td>
                <td>
                    <?= $e['title'].' '.$e['multimedia'] ?>
                </td>
                <td>
                    <?= $e['user'] ?>
                </td>
                <td>
                    <?= $e['phone'] ?>
                </td>
                <td>
                    <?= $e['email']?>
                </td>
                <td>
                    <?= $e['other'] ?>
                </td>
                <td>
                    <!-- TODO: needed from backend -->
                </td>
                <td>
                    <a href="" onclick="open_show_event(<?= "$this->room_id, $e[real_id]" ?>); return false;">Разгледай</a>
                    <a href="" onclick="open_edit_event(<?= "$this->room_id, $e[real_id]" ?>); return false;">Редактирай</a>
                    <a href="/delete_events?room_id=<?= $this->room_id ?>&event=<?= $e['real_id'] ?>" onclick="return confirm_delete_event();">Изтрии</a>
                </td>
            </tr>
        <?php } ?>
    </table>
    <input type="hidden" value="<?= $this->room_id ?>" name="room_id" />
    <input type="button" value="Принтирай" onclick="print();" />
    <input type="submit" value="Изтрий избраните" onclick="return confirm_delete_events();" />
</form>