<form style="max-width:80%;" class="light" method="dialog" id="repeat_form" onsubmit="submit_repeat();">
    <h2 class="mb-3">
        Повтаряне на събитието
    </h2>
    <p>
        <label for="repeat">Да се повтаря:</label>
        <select name="repeat" class="form-control" onchange="on_repeat_change(this);">
            <option value="never">Никога</option>
            <option value="weekly">Седмично</option>
            <option value="monthly">Месечно</option>
        </select>
    </p>
    <div id="repeat_details" style="display: none;">
        <p id="weekly_repeat">
            <label for="weekly_repeat">На колко седмици да се повтаря:</label>
            <input type="number" min="1" max="4" value="1" name="weekly_repeat" class="form-control" />
        </p>
        <p>
            Дни, в които да се повтаря:<br />
            <input type="checkbox" name="repeat_day" value="mon" />Пн
            <input type="checkbox" name="repeat_day" value="tue" />Вт
            <input type="checkbox" name="repeat_day" value="wed" />Ср
            <input type="checkbox" name="repeat_day" value="thu" />Чт
            <input type="checkbox" name="repeat_day" value="fri" />Пт
            <input type="checkbox" name="repeat_day" value="sat" />Сб
            <input type="checkbox" name="repeat_day" value="sun" />Нд
        </p>
        <p>
            <label for="repeat_start">Начало:</label>
            <input class="form-control" type="date" min="<?= $this->min_date ?>" value="<?= $this->repeat_start ?>" name="repeat_start" />
        </p>
        <p>
            <label for="repeat_end">Край:</label>
            <select name="repeat_end" class="form-control" onchange="on_repeat_end_change(this);">
                <option value="never">Никога</option>
                <option value="count">След брой провеждания</option>
                <option value="date">На дата</option>
            </select>
        </p>
        <p id="repeat_end_count" style="display: none;">
            <label for="repeat_end_count">След брой провеждания:</label>
            <input type="number" min="1" value="1" name="repeat_end_count" class="form-control" />
        </p>
        <p id="repeat_end_date" style="display: none;">
            <label for="repeat_end_date">Крайна дата:</label>
            <input class="form-control" type="date" min="<?= $this->min_date ?>" value="<?= $this->repeat_start ?>" name="repeat_end_date" />
        </p>
    </div>

    <p class="mb-0 text-right">
        <input type="buttom" class="btn" value="Отказ" onClick="close_popup();" />
        <input type="submit" class="btn btn-primary" value="Приложи" />
    </p>
</form>
