<?php
# default stylesheets
$stylesheets = array_merge($this->stylesheets ? $this->stylesheets : [], [
'common.css',
'bootstrap.css',
'jquery.fancybox.min.css',
]);

# default scripts
$scripts = array_merge($this->scripts ? $this->scripts : [], [
    'jquery-3.4.1.min.js',
    'cookie.umd.min.js',
    'jquery.fancybox.min.js',
    'common.js',
]);
?>

<!DOCTYPE html>
<html>

<head>
    <meta charset="UTF-8">
    <meta http-equiv="x-ua-compatible" content="IE=edge" />
    <title><?= $this->title ?></title>
    <?php foreach (($this->head_elements ? $this->head_elements : []) as $e) {
        echo $e;
    }
    ?>

    <?php foreach ($stylesheets as $e) { ?>
        <link rel="stylesheet" type="text/css" href="/resources/stylesheets/<?= $e ?>" />
    <?php } ?>

    <?php foreach ($scripts as $e) { ?>
        <script src="/resources/scripts/<?= $e ?>"></script>
    <?php } ?>
</head>

<body>
    <header>
        <div>
            <h1><?= $this->title ?></h1>
            <h4><a href="/">Списък на залите</a> | <a href="">Семинарна зала</a> | <a href="">Заявки</a></h4>
        </div>
    </header>
    <div id="content">
