<form style="max-width:80%;" id="event_form" method="post" action="/new_room_post" class="light" onsubmit="on_event_submit();">
    <h2>Създаване на календар за нова зала</h2>
    <p>
        <label for="name" class="required">Наименование на залата:</label>
        <input class="form-control" type="text" name="name" required />
    </p>
    <p>
        <label for="image_path">URL на картинката:</label>
        <input class="form-control" type="text" name="image_path" />
    </p>
    <p>
        <label for="color">Цвят:</label>
        <input class="form-control" type="color" name="color" value="#900000" />
    </p>

    <p class="mb-0 text-right">
        <input type="submit" class="btn btn-primary" value="Създай" />
    </p>
</form>
