<div class="grid-container">

<?php
foreach ($this->rooms as $room_id => $room) {
?>
<div class="grid-element">
    <a href="<?= ($room_id === 'new' ? 'javascript:open_ajax_popup(\'/new_room\');' : "/rooms/$room_id") ?>">
        <div class="icon shadowed">
            <img src="/resources/images/<?= $room['img_url'] ?>" class="<?php if (isset($room['img_class'])) { echo $room['img_class']; } ?>"/>
        </div>
        <div><?= $room['title'] ?></div>
    </a>
</div>
<?php
}
?>

</div>
